name = "欧皇模拟器 随机海钓 综合补丁" -- Mod的名字
author = "我好慌" -- 作者名
description = "抽奖机综合补丁，\n金币兑换抽奖币,\n金币兑换附魔物品,\n金币兑换海钓浮漂,\n商店全物品,\n自定义的超多金币数量,\n可调商店物品倍率,\n可调金币爆率 \n输入#ql清理自动回收金币（参考3628068817）, \n可选是否开启击杀金币掉落自动入账,  \nPS 金币兑换物品时，金币必须放在物品栏" -- Mod描述

version = "1.17"
forumthread = ""
api_version = 10

dst_compatible = true
all_clients_require_mod = true
priority = -20005  -- 加载优先级

icon_atlas = "modicon.xml"
icon = "modicon.tex"

server_filter_tags = {
    "抽奖机", "中文", "随机海钓", "海钓随机物品", "欧皇模拟器", "补丁", "兑换"
}

configuration_options = {
    {
        name = "dh_enable_exchange",
        label = "允许兑换",
        hover = "是否允许使用金币兑换物品",
        options = {
            {description = "开启", data = true, hover = "允许兑换"},
            {description = "关闭", data = false, hover = "禁止兑换"},
        },
        default = true,
    },
    {
        name = "dh_enable_exchange_slotmachine",
        label = "允许兑换抽奖机相关物品",
        hover = "是否允许兑换随机币/10倍币/厄运币/幸运币",
        options = {
            {description = "开启", data = true, hover = "允许兑换抽奖机相关物品"},
            {description = "关闭", data = false, hover = "禁止兑换抽奖机相关物品"},
        },
        default = true,
    },
    {
        name = "dh_enable_exchange_enchant",
        label = "允许兑换附魔相关物品",
        hover = "是否允许兑换寻宝卷轴/水晶小人/附魔卷轴/洗蕴石",
        options = {
            {description = "开启", data = true, hover = "允许兑换附魔相关物品"},
            {description = "关闭", data = false, hover = "禁止兑换附魔相关物品"},
        },
        default = true,
    },
    {
        name = "dh_enable_exchange_bobber",
        label = "允许兑换浮漂相关物品",
        hover = "是否允许兑换海钓浮漂类物品",
        options = {
            {description = "开启", data = true, hover = "允许兑换浮漂相关物品"},
            {description = "关闭", data = false, hover = "禁止兑换浮漂相关物品"},
        },
        default = true,
    },
    {
        name = "dh_ohmnq_shop_sell_all",
        label = "商店全售卖",
        hover = "是否让抽奖机商店显示全部可售物品(不再随机刷新)",
        options = {
            {description = "开启", data = true, hover = "商店显示全部可售物品"},
            {description = "关闭", data = false, hover = "商店按原规则随机售卖部分物品"},
        },
        default = true,
    },
    {
        name = "dh_ohmnq_start_dubloon_enable",
        label = "开局礼包添加金币",
        hover = "是否在开局礼包中额外添加金币",
        options = {
            {description = "开启", data = true, hover = "开局礼包额外添加金币"},
            {description = "关闭", data = false, hover = "不额外添加金币"},
        },
        default = true,
    },
    {
        name = "dh_ohmnq_start_dubloon_amount",
        label = "开局礼包金币数量",
        hover = "开局礼包额外添加的金币数量",
        options = {
            {description = "100", data = 100, hover = "额外添加100个金币"},
            {description = "500", data = 500, hover = "额外添加500个金币"},
            {description = "1000", data = 1000, hover = "额外添加1000个金币"},
            {description = "2000", data = 2000, hover = "额外添加2000个金币"},
            {description = "5000", data = 5000, hover = "额外添加5000个金币"},
            {description = "10000", data = 10000, hover = "额外添加10000个金币"},
            {description = "100000", data = 100000, hover = "额外添加100000个金币"},
        },
        default = 1000,
    },
    {
        name = "dh_ohcoinrandom",
        label = "每个抽奖机随机币所需要的金币数量",
        hover = "每个抽奖机随机币所需要的金币数量",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个随机币"},
            {description = "2", data = 2, hover = "2个金币兑换1个随机币"},
            {description = "3", data = 3, hover = "3个金币兑换1个随机币"},
            {description = "5", data = 5, hover = "5个金币兑换1个随机币"},
            {description = "8", data = 8, hover = "8个金币兑换1个随机币"},
            {description = "10", data = 10, hover = "10个金币兑换1个随机币"},
            {description = "20", data = 20, hover = "20个金币兑换1个随机币"},
            {description = "40", data = 40, hover = "40个金币兑换1个随机币"},
            {description = "100", data = 100, hover = "100个金币兑换1个随机币"},
        },
        default = 10,
    },
    {
        name = "dh_ohcoin10",
        label = "每个抽奖机10倍币所需要的金币数量",
        hover = "每个抽奖机10倍币所需要的金币数量",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个10倍币"},
            {description = "2", data = 2, hover = "2个金币兑换1个10倍币"},
            {description = "3", data = 3, hover = "3个金币兑换1个10倍币"},
            {description = "5", data = 5, hover = "5个金币兑换1个10倍币"},
            {description = "8", data = 8, hover = "8个金币兑换1个10倍币"},
            {description = "10", data = 10, hover = "10个金币兑换1个10倍币"},
            {description = "20", data = 20, hover = "20个金币兑换1个10倍币"},
            {description = "40", data = 40, hover = "40个金币兑换1个10倍币"},
            {description = "100", data = 100, hover = "100个金币兑换1个10倍币"},
        },
        default = 10,
    },
    {
        name = "dh_ohcoincursed",
        label = "每个抽奖机厄运币所需要的金币数量",
        hover = "每个抽奖机厄运币所需要的金币数量",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换10个厄运币"},
            {description = "2", data = 2, hover = "2个金币兑换10个厄运币"},
            {description = "3", data = 3, hover = "3个金币兑换10个厄运币"},
            {description = "5", data = 5, hover = "5个金币兑换10个厄运币"},
            {description = "8", data = 8, hover = "8个金币兑换10个厄运币"},
            {description = "10", data = 10, hover = "10个金币兑换10个厄运币"},
            {description = "20", data = 20, hover = "20个金币兑换10个厄运币"},
            {description = "40", data = 40, hover = "40个金币兑换10个厄运币"},
            {description = "100", data = 100, hover = "100个金币兑换1个厄运币"},
        },
        default = 10,
    },
    {
        name = "dh_ohcoinlucky",
        label = "每个抽奖机幸运币所需要的金币数量",
        hover = "每个抽奖机幸运币所需要的金币数量",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换10个幸运币"},
            {description = "2", data = 2, hover = "2个金币兑换10个幸运币"},
            {description = "3", data = 3, hover = "3个金币兑换10个幸运币"},
            {description = "5", data = 5, hover = "5个金币兑换10个幸运币"},
            {description = "8", data = 8, hover = "8个金币兑换10个幸运币"},
            {description = "10", data = 10, hover = "10个金币兑换10个幸运币"},
            {description = "20", data = 20, hover = "20个金币兑换10个幸运币"},
            {description = "40", data = 40, hover = "40个金币兑换10个幸运币"},
            {description = "100", data = 100, hover = "100个金币兑换1个幸运币"},
        },
        default = 10,
    },
    {
        name = "dh_hh_treasure_tally",
        label = "每个寻宝卷轴所需要的金币数量",
        hover = "每个寻宝卷轴所需要的金币数量",
        options = {
            {description = "10", data = 10, hover = "10个金币兑换1个寻宝卷轴"},
            {description = "20", data = 20, hover = "20个金币兑换1个寻宝卷轴"},
            {description = "50", data = 50, hover = "50个金币兑换1个寻宝卷轴"},
            {description = "100", data = 100, hover = "100个金币兑换1个寻宝卷轴"},
            {description = "200", data = 200, hover = "200个金币兑换1个寻宝卷轴"},
            {description = "400", data = 400, hover = "400个金币兑换1个寻宝卷轴"},
        },
        default = 100,
    },
    {
        name = "dh_hh_essence",
        label = "每个水晶小人所需要的金币数量",
        hover = "每个水晶小人所需要的金币数量",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个水晶小人"},
            {description = "2", data = 2, hover = "2个金币兑换1个水晶小人"},
            {description = "3", data = 3, hover = "3个金币兑换1个水晶小人"},
            {description = "5", data = 5, hover = "5个金币兑换1个水晶小人"},
            {description = "8", data = 8, hover = "8个金币兑换1个水晶小人"},
            {description = "10", data = 10, hover = "10个金币兑换1个水晶小人"},
            {description = "20", data = 20, hover = "20个金币兑换1个水晶小人"},
            {description = "40", data = 40, hover = "40个金币兑换1个水晶小人"},
            {description = "100", data = 100, hover = "100个金币兑换1个水晶小人"},
        },
        default = 20,
    },
    {
        name = "dh_hh_effect_tally",
        label = "每个附魔卷轴所需要的金币数量",
        hover = "每个附魔卷轴所需要的金币数量",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个附魔卷轴"},
            {description = "2", data = 2, hover = "2个金币兑换1个附魔卷轴"},
            {description = "3", data = 3, hover = "3个金币兑换1个附魔卷轴"},
            {description = "5", data = 5, hover = "5个金币兑换1个附魔卷轴"},
            {description = "8", data = 8, hover = "8个金币兑换1个附魔卷轴"},
            {description = "10", data = 10, hover = "10个金币兑换1个附魔卷轴"},
            {description = "20", data = 20, hover = "20个金币兑换1个附魔卷轴"},
            {description = "40", data = 40, hover = "40个金币兑换1个附魔卷轴"},
            {description = "100", data = 100, hover = "100个金币兑换1个附魔卷轴"},
        },
        default = 10,
    },
    {
        name = "dh_hh_remove_stone",
        label = "每个洗蕴石所需要的金币数量",
        hover = "每个洗蕴石所需要的金币数量",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个洗蕴石"},
            {description = "2", data = 2, hover = "2个金币兑换1个洗蕴石"},
            {description = "3", data = 3, hover = "3个金币兑换1个洗蕴石"},
            {description = "5", data = 5, hover = "5个金币兑换1个洗蕴石"},
            {description = "8", data = 8, hover = "8个金币兑换1个洗蕴石"},
            {description = "10", data = 10, hover = "10个金币兑换1个洗蕴石"},
            {description = "20", data = 20, hover = "20个金币兑换1个洗蕴石"},
            {description = "40", data = 40, hover = "40个金币兑换1个洗蕴石"},
            {description = "100", data = 100, hover = "100个金币兑换1个洗蕴石"},
        },
        default = 10,
    },
    {
        name = "dh_bobber_price_twigs",
        label = "树枝(海钓排除物品表)定价",
        hover = "设置树枝浮漂的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个树枝"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个树枝"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个树枝"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个树枝"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个树枝"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个树枝"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个树枝"}},
        default = 1,
    },
    {
        name = "dh_bobber_price_ball",
        label = "木球浮标(海钓排除事件表)定价",
        hover = "设置木球浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个木球浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个木球浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个木球浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个木球浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个木球浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个木球浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个木球浮标"}},
        default = 1,
    },
    {
        name = "dh_bobber_price_oval",
        label = "硬物浮标(海钓排除穿戴表)定价",
        hover = "设置PhysRev浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个PhysRev浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个PhysRev浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个PhysRev浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个PhysRev浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个PhysRev浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个PhysRev浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个PhysRev浮标"}},
        default = 1,
    },
    {
        name = "dh_bobber_price_trinket_8",
        label = "橡胶塞(海钓双倍钓取)定价",
        hover = "设置橡胶塞浮漂的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个橡胶塞"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个橡胶塞"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个橡胶塞"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个橡胶塞"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个橡胶塞"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个橡胶塞"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个橡胶塞"}},
        default = 5,
    },
    {
        name = "dh_bobber_price_robin",
        label = "红羽浮标(海钓排除食材表)定价",
        hover = "设置红羽浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个红羽浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个红羽浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个红羽浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个红羽浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个红羽浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个红羽浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个红羽浮标"}},
        default = 1,
    },
    {
        name = "dh_bobber_price_canary",
        label = "黄羽浮标(海钓排除种植表)定价",
        hover = "设置黄羽浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个黄羽浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个黄羽浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个黄羽浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个黄羽浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个黄羽浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个黄羽浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个黄羽浮标"}},
        default = 1,
    },
    {
        name = "dh_bobber_price_crow",
        label = "黑羽浮标(海钓排除生物表)定价",
        hover = "设置黑羽浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个黑羽浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个黑羽浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个黑羽浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个黑羽浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个黑羽浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个黑羽浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个黑羽浮标"}},
        default = 1,
    },
    {
        name = "dh_bobber_price_robin_winter",
        label = "蔚蓝浮标(海钓排除建筑表)定价",
        hover = "设置蔚蓝浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个蔚蓝浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个蔚蓝浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个蔚蓝浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个蔚蓝浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个蔚蓝浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个蔚蓝浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个蔚蓝浮标"}},
        default = 1,
    },
    {
        name = "dh_bobber_price_goose",
        label = "鹅羽浮标(海钓排除材料表)定价",
        hover = "设置鹅羽浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个鹅羽浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个鹅羽浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个鹅羽浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个鹅羽浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个鹅羽浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个鹅羽浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个鹅羽浮标"}},
        default = 10,
    },
    {
        name = "dh_bobber_price_malbatross",
        label = "邪天翁浮标(海钓排除巨兽表)定价",
        hover = "设置邪天翁浮标的兑换价格",
        options = {
            {description = "1", data = 1, hover = "1个金币兑换1个邪天翁浮标"}, 
            {description = "2", data = 2, hover = "2个金币兑换1个邪天翁浮标"}, 
            {description = "5", data = 5, hover = "5个金币兑换1个邪天翁浮标"}, 
            {description = "10", data = 10, hover = "10个金币兑换1个邪天翁浮标"}, 
            {description = "20", data = 20, hover = "20个金币兑换1个邪天翁浮标"}, 
            {description = "50", data = 50, hover = "50个金币兑换1个邪天翁浮标"}, 
            {description = "100", data = 100, hover = "100个金币兑换1个邪天翁浮标"}},
        default = 10,
    },
    {
        name = "dh_shop_price_rate",
        label = "商店价格倍率",
        hover = "调整抽奖机商店所有物品的买入价格倍率",
        options = {
            {description = "0.1倍", data = 0.1, hover = "价格变为原来的10%"},
            {description = "0.2倍", data = 0.1, hover = "价格变为原来的20%"},
            {description = "0.3倍", data = 0.1, hover = "价格变为原来的30%"},
            {description = "0.4倍", data = 0.1, hover = "价格变为原来的40%"},
            {description = "0.5倍", data = 0.5, hover = "价格变为原来的50%"},
            {description = "0.8倍", data = 0.8, hover = "价格变为原来的80%"},
            {description = "1.0倍(默认)", data = 1.0, hover = "原始价格"},
            {description = "1.2倍", data = 1.2, hover = "价格提高20%"},
            {description = "1.5倍", data = 1.5, hover = "价格提高50%"},
            {description = "2.0倍", data = 2.0, hover = "价格翻倍"},
            {description = "5.0倍", data = 5.0, hover = "价格变为5倍"},
            {description = "10.0倍", data = 10.0, hover = "价格变为10倍"},
        },
        default = 1.0,
    },
    {
        name = "dh_enable_smart_recycle",
        label = "清理物品时回收",
        hover = "使用 #ql 命令清理物品时是否将其回收为金币。",
        options = {
            {description = "是", data = true, hover = "清理时回收物品"},
            {description = "否", data = false, hover = "清理时直接删除物品"},
        },
        default = true,
    },
    {
        name = "dh_kill_to_deposit",
        label = "击杀掉落金币直接存款",
        hover = "击杀怪物掉落的金币是否直接存入玩家账户。",
        options = {
            {description = "是", data = true, hover = "金币直接存入账户"},
            {description = "否", data = false, hover = "金币掉落在地上"},
        },
        default = true,
    },
    {
        name = "dh_coins_explosion_rate_mult",
        label = "额外金币爆率倍率",
        hover = "在欧皇模拟器原有的爆率基础上，额外乘以一个倍率。",
        options = {
            {description = "0.1倍", data = 0.1},
            {description = "0.5倍", data = 0.5},
            {description = "1.0倍(默认)", data = 1.0},
            {description = "1.5倍", data = 1.5},
            {description = "2.0倍", data = 2.0},
            {description = "3.0倍", data = 3.0},
            {description = "5.0倍", data = 5.0},
            {description = "10.0倍", data = 10.0},
            {description = "20.0倍", data = 20.0},
            {description = "50.0倍", data = 50.0},
            {description = "100.0倍", data = 100.0},
        },
        default = 1.0,
    }
}
